nodeLinker: node-modules

compressionLevel: mixed
enableGlobalCache: false

enableStrictSsl: false

npmScopes:
  appdev-platform:
    npmRegistryServer: 'https://nexus.corp.redhat.com/repository/appdev-platform/'
    npmAlwaysAuth: true
  compass:
    npmRegistryServer: 'https://nexus.corp.redhat.com/repository/compass/'
    npmAlwaysAuth: true
  appdev:
    npmRegistryServer: 'https://nexus.corp.redhat.com/repository/compass/'
    npmAlwaysAuth: true

npmPublishRegistry: https://nexus.corp.redhat.com/repository/compass/
npmAuthIdent: ${COMPASS_NEXUS_TOKEN:-dummy-fallback}

injectEnvironmentFiles:
  - .env?

enableTransparentWorkspaces: false
