nodeLinker: node-modules

compressionLevel: mixed
enableGlobalCache: false

enableStrictSsl: false

npmScopes:
  appdev-platform:
    npmRegistryServer: 'https://nexus.corp.redhat.com/repository/appdev-platform/'
    npmAlwaysAuth: true
  compass:
    npmRegistryServer: 'https://nexus.corp.redhat.com/repository/compass/'
    npmAlwaysAuth: true
  appdev:
    npmRegistryServer: 'https://nexus.corp.redhat.com/repository/compass/'
    npmAlwaysAuth: true

injectEnvironmentFiles:
  - .env?
