apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-plugins
spec:
  owner: group:redhat/one-platform-devs
  lifecycle: producion
  targets:
    - ./plugins/analytics-module-matomo/catalog-info.yaml
    - ./plugins/cmdb/catalog-info.yaml
    - ./plugins/lighthouse/catalog-info.yaml
    - ./plugins/matomo/catalog-info.yaml
    - ./plugins/matomo-backend/catalog-info.yaml
    - ./plugins/spaship/catalog-info.yaml
