- https://gitlab.cee.redhat.com/dxp/dx-pulse/soundcheck-config/-/raw/main/prod/checks/business-risk.yaml
- https://gitlab.cee.redhat.com/dxp/dx-pulse/soundcheck-config/-/raw/main/preprod/checks/drupal-platform.yaml
